- id: orojo-vulnerability-forecasting-2024
  type: paper
  title: "Predicting Software Vulnerability Trends with Multi-Recurrent Neural Networks: A Time Series Forecasting Approach"
  authors:
    - A Orojo
    - W Elumelu
    - O Orojo
    - M Donnahoo
    - S Hutton
  publisher: The International Conference on Natural Language Processing and Artificial Intelligence
  date: 2024-01-01
  description: "Research exploring time series forecasting methods to predict software vulnerability trends using multi-recurrent neural networks."
  tags:
    - vulnerability prediction
    - neural networks
    - time series forecasting

- id: orojo-unified-framework-2024
  type: paper
  title: "A Unified Framework Incorporating AW-TRBAC and Semantic Variational Autoencoders for Dynamic Threat Detection and Access Control"
  authors:
    - A Orojo
    - E El-Mahmoud
    - S Hutton
    - W Elumelu
    - M Donahoo
  publisher: DCS-Water 2024 1 (1)
  date: 2024-01-01
  description: "This paper introduces a composite framework that integrates Dynamic Access Control and Intrusion Detection Systems with a focus on enhancing cyber resilience in Cyber Physical Systems."
  tags:
    - threat detection
    - access control
    - autoencoders
    - cyber resilience

- id: orojo-intrusion-detection-2023
  type: paper
  title: "Advancing Network Intrusion Detection with a Sliding Window-Based CNN and CFS-BA Feature Selection"
  authors:
    - A Orojo
  publisher: ResearchGate
  date: 2023-01-01
  description: "This research proposes an efficient network intrusion detection system using sliding window-based CNN and feature selection techniques to enhance detection accuracy."
  tags:
    - intrusion detection
    - CNN
    - feature selection
    - cybersecurity

- id: orojo-digital-maze-2022
  type: paper
  title: "Navigating the Digital Maze: Exploring the Intersection of Social Media, Privacy, and Security"
  authors:
    - A Orojo
  publisher: Webster University
  date: 2022-01-01
  description: "This study examines the complex relationships between social media usage, privacy concerns, and security implications in the digital age."
  tags:
    - social media
    - privacy
    - security
    - digital ethics